{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:202341164",
  "Version": "636",
  "Metadata": {
    "Title": "Potential denial of service vulnerability in  ``django.utils.encoding.uri_to_iri()`` (moderate)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2023-41164",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2023-41164"
      }
    ],
    "Description": "DOCUMENTATION: No description is available for this CVE.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Moderate",
      "Issued": {},
      "Updated": {
        "Date": "2023-09-05"
      },
      "Cves": [
        {
          "CveID": "CVE-2023-41164",
          "Cvss3": "6.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
          "Cwe": "CWE-400",
          "Impact": "moderate",
          "Href": "https://access.redhat.com/security/cve/CVE-2023-41164",
          "Public": "20230904"
        }
      ],
      "AffectedCpeList": [
        "cpe:/a:redhat:openstack:17.0",
        "cpe:/a:redhat:openstack:17.0::el9"
      ],
      "Affected": {
        "Resolution": {
          "State": "Out of support scope"
        }
      }
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20213563006"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 9 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20213563005"
          },
          {
            "Comment": "python3-django is installed",
            "TestRef": "oval:com.redhat.cve:tst:202323969001"
          },
          {
            "Comment": "python3-django is signed with Red Hat redhatrelease2 key",
            "TestRef": "oval:com.redhat.cve:tst:202323969002"
          }
        ]
      }
    ]
  }
}