{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-29T00:00:00Z",
      "advisory": "RHSA-2023:7581",
      "package": "postgresql:13-8090020231114113712.a75119d5",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.6 Extended Update Support",
      "release_date": "2023-11-29T00:00:00Z",
      "advisory": "RHSA-2023:7580",
      "package": "postgresql:13-8060020231114115246.ad008a3a",
      "cpe": "cpe:/a:redhat:rhel_eus:8.6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.8 Extended Update Support",
      "release_date": "2023-11-29T00:00:00Z",
      "advisory": "RHSA-2023:7579",
      "package": "postgresql:13-8080020231114105206.63b34585",
      "cpe": "cpe:/a:redhat:rhel_eus:8.8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9.0 Extended Update Support",
      "release_date": "2023-11-28T00:00:00Z",
      "advisory": "RHSA-2023:7545",
      "package": "postgresql-0:13.13-1.el9_0",
      "cpe": "cpe:/a:redhat:rhel_eus:9.0"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9.2 Extended Update Support",
      "release_date": "2023-11-30T00:00:00Z",
      "advisory": "RHSA-2023:7616",
      "package": "postgresql-0:13.13-1.el9_2",
      "cpe": "cpe:/a:redhat:rhel_eus:9.2"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Affected",
      "package_name": "postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "postgresql:10/postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "postgresql:12/postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "postgresql:15/postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "postgresql:15/postgresql",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-postgresql10-postgresql",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-postgresql12-postgresql",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Affected",
      "package_name": "rh-postgresql13-postgresql",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-11-09T00:00:00Z",
  "bugzilla": {
    "description": "postgresql: Memory disclosure in aggregate function calls",
    "id": "2247168",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2247168"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "4.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
    "status": "verified"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "Upstream acknowledges Jingzhou Fu as the original reporter.",
  "name": "CVE-2023-5868",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-5868\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-5868\nhttps://www.postgresql.org/about/news/postgresql-161-155-1410-1313-1217-and-1122-released-2749/\nhttps://www.postgresql.org/support/security/CVE-2023-5868/"
  ]
}