{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Under investigation",
      "package_name": "python-pillow",
      "cpe": "cpe:/a:redhat:satellite:6"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2024-01-19T00:00:00Z",
  "bugzilla": {
    "description": "pillow:Arbitrary Code Execution via the environment parameter",
    "id": "2259479",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2259479"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-50447",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-50447\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-50447\nhttp://www.openwall.com/lists/oss-security/2024/01/20/1\nhttps://devhub.checkmarx.com/cve-details/CVE-2023-50447/\nhttps://duartecsantos.github.io/2023-01-02-CVE-2023-50447/\nhttps://github.com/python-pillow/Pillow/releases"
  ]
}