{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "frr",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "frr",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.0",
      "fix_state": "Will not fix",
      "package_name": "frr",
      "cpe": "cpe:/a:redhat:openstack:17.0"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Will not fix",
      "package_name": "frr",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-08-29T00:00:00Z",
  "bugzilla": {
    "description": "frr: out of bounds read in bgp_attr_aigp_valid",
    "id": "2235840",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2235840"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-41359",
  "document_distribution": "",
  "details": [
    "An issue was discovered in FRRouting FRR through 9.0. There is an out-of-bounds read in bgp_attr_aigp_valid in bgpd/bgp_attr.c because there is no check for the availability of two bytes during AIGP validation."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-41359\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-41359\nhttps://github.com/FRRouting/frr/pull/14232"
  ]
}