{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "automation-controller",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python3x-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python3x-cryptography",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python-cryptography",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ceph Storage 4",
      "fix_state": "Under investigation",
      "package_name": "ansible-runner-service",
      "cpe": "cpe:/a:redhat:ceph_storage:4"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "rhcertification/redhat-certification-baremetal",
      "cpe": "cpe:/a:redhat:certifications:1::el8"
    },
    {
      "product_name": "Red Hat Discovery",
      "fix_state": "Under investigation",
      "package_name": "discovery/discovery-server-rhel8",
      "cpe": "cpe:/a:redhat:discovery:1.0::el8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python3.11-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python39:3.9/python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "python3.11-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "python-cryptography",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "quay/quay-rhel8",
      "cpe": "cpe:/a:redhat:quay:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "rh-python38-python-cryptography",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Under investigation",
      "package_name": "python-cryptography",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-11-28T00:00:00Z",
  "bugzilla": {
    "description": "python-cryptography: NULL-dereference when loading PKCS7 certificates",
    "id": "2255331",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2255331"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.9",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-476",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-49083",
  "document_distribution": "",
  "details": [
    "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-49083\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-49083\nhttps://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a\nhttps://github.com/pyca/cryptography/pull/9926\nhttps://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97"
  ]
}